# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: YC-queue-handler deploy
        uses: yc-actions/yc-sls-function@v4.1.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          yc-sa-id: ${{ secrets.YC_SA_ID }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'goha'
          runtime: 'golang123'
          memory: '512Mb'
          execution-timeout: 30
          service-account: ${{ secrets.YC_SA_ID }}
          entrypoint: 'index.QueueHandler'
          source-root: '.'
          environment: |
            YDB_METADATA_CREDENTIALS=1
            YDB_CONNECTION_STRING=${{ secrets.YDB_CONNECTION }}
          include: |
            ./*.go
            ./go.mod
            ./go.sum

      - name: YC-webhook deploy
        uses: yc-actions/yc-sls-function@v4.1.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          yc-sa-id: ${{ secrets.YC_SA_ID }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'goha-webhook'
          runtime: 'golang123'
          memory: '256Mb'
          execution-timeout: 10
          service-account: ${{ secrets.YC_SA_ID }}
          entrypoint: 'index.WebhookHandler'
          source-root: '.'
          environment: |
            YDB_METADATA_CREDENTIALS=1
            YDB_CONNECTION_STRING=${{ secrets.YDB_CONNECTION }}
            DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
          include: |
            ./*.go
            ./go.mod
            ./go.sum
          # tags: |
          #   ${{ GITHUB_SHA::6 }}
          #   foo
          # secrets: |
            # DB_PASSWORD=lockbox-secret-id/latest/password
            # API_KEY=lockbox-secret-id/abcdef123456/api_key
